<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Title>Konoobi Voice Trigger</Title>
    <Copyright>SANDCorp, Shade of Singularity (SoG)</Copyright>
    <LangVersion>preview</LangVersion>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <PackageVersion>$(Version)</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Cubism\**" />
    <EmbeddedResource Remove="Cubism\**" />
    <None Remove="Cubism\**" />
    <Page Remove="Cubism\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
    <None Remove="Resources\Avatar\Source\imad.png" />
    <None Remove="Resources\Avatar\Source\imald.png" />
    <None Remove="Resources\Avatar\Source\kocalm.png" />
    <None Remove="Resources\Avatar\Source\komald.png" />
    <None Remove="Resources\Avatar\Source\kotalk.png" />
    <None Remove="Resources\Avatar\Source\koyap.png" />
    <None Remove="Resources\Emotes\kobi-blind.png" />
    <None Remove="Resources\ibok-active.png" />
    <None Remove="Resources\ibok-normal-unused.png" />
    <None Remove="Resources\ibok-normal.png" />
    <None Remove="Resources\kobi-active.png" />
    <None Remove="Resources\kobi-normal.png" />
    <None Remove="Shaders\MonochromeShader.hlsl" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Avatar\Source\imad.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\imald.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\imald-aura.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\kocalm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\komald.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\kotalk.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Avatar\Source\koyap.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Emotes\kobi-blind.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="JeremyAnsel.HLSL.Targets" Version="2.0.35" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <!--<PackageReference Include="VTS-Sharp" Version="2.4.1" />-->
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="Styles\" />
  </ItemGroup>
	
  <ItemGroup>
    <HLSLShader Include="Shaders\MonochromeShader.hlsl">
      <ShaderProfile>ps_2_0</ShaderProfile>
      <TreatWarningAsError>True</TreatWarningAsError>
      <Debug>False</Debug>
      <OutputDisassembly>True</OutputDisassembly>
    </HLSLShader>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Windows" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Emotes\ibok-active.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Emotes\ibok-normal-unused.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Emotes\ibok-normal.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Emotes\kobi-active.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Emotes\kobi-normal.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
