<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Title>Konoobi Voice Trigger</Title>
    <Copyright>SANDCorp, Shade of Singularity (SoG)</Copyright>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Cubism\**" />
    <EmbeddedResource Remove="Cubism\**" />
    <None Remove="Cubism\**" />
    <Page Remove="Cubism\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
    <None Remove="Resources\ibok-active.png" />
    <None Remove="Resources\ibok-normal.png" />
    <None Remove="Resources\kobi-active.png" />
    <None Remove="Resources\kobi-normal.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\ibok-active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ibok-normal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\kobi-active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\kobi-normal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <!--<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />-->
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="Shaders\" />
    <Folder Include="Styles\" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Windows" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
